### ISSUE TITLE
Restart Button Is Not Working 

### ISSUE THREAD

**Issue by PATILYASHH** [YadavAkhileshh/Alien-Invasion-Defense#1]
#The restart button is hidden behind the Game Over Massage 

** Sreenshot **
![image](https://github.com/user-attachments/assets/3d3213a0-5568-4e6d-97e0-abfdb8605c04)

**Comment by PATILYASHH** [comment]
Please assign me for this issue

**Comment by ysachin438** [comment]
Hi @YadavAkhileshh, I would like work on and fix the issue of restart button. Please assign me.

**Comment by YadavAkhileshh** [comment]
@ysachin438 This issue has been resolved, so you can proceed with the new issue and begin working on it.
