### ISSUE TITLE
Overlaping of the cards

### ISSUE THREAD

**Issue by jayanththalla** [YadavAkhileshh/Alien-Invasion-Defense#10]
The cards are overlapping
![image](https://github.com/user-attachments/assets/35b93634-2feb-4ff6-9774-8d41580917ff)

**Comment by HarshitShukla-dev** [comment]
hey @YadavAkhileshh can you please assign this issue to me? I would love to work on this.

**Comment by Deepthi-Ramineni** [comment]
Can you please assign this issue to me? I would like to work on it.
