### ISSUE TITLE
Adding Custom Cursor effect

### ISSUE THREAD

**Issue by ShrishtiSingh26** [YadavAkhileshh/Alien-Invasion-Defense#101]
### Unique cursor designs can capture users' attention and make the interaction, encouraging them to engage more with your content.

Please assign this to me , I am ready for this under Hacktoberfest and GSSOC extd
Thankyou!

**Comment by Akanshaku** [comment]
I would like to work on this pls assign me this under GSSoC'24 Extd @YadavAkhileshh

**Comment by ShrishtiSingh26** [comment]
@YadavAkhileshh I have pushed the changes and resolved all the conflicts hope you will merge the PR soon 
Do add the labels of gssoc and hacktober to the PR 

thank you!
