### ISSUE TITLE
playing game onli after signing up

### ISSUE THREAD

**Issue by keerthana2-005** [YadavAkhileshh/Alien-Invasion-Defense#113]
i can see that u can play the game even without signing up  and plz add lables gssoc extended and hacktoberfest and level labels (3)

**Comment by AKSHITHA-CHILUKA** [comment]
wrong label is mentioned 
level3 is the crt one without space 
please change 
Community Manager this side

**Comment by jjf2009** [comment]
@YadavAkhileshh if the issue is open can i work on it

**Comment by keerthana2-005** [comment]
Resilved

**Comment by AKSHITHA-CHILUKA** [comment]
may I know why level3 label @YadavAkhileshh 
where is the closing pr??
