### ISSUE TITLE
change bg of website

### ISSUE THREAD

**Issue by priyanshu1976** [YadavAkhileshh/Alien-Invasion-Defense#119]
The background looks soo simple in compared to the game i can make a more asthetic and scifi bg bg for your website please assign me this issue under hacktober fest accepted

**Comment by sayiamarora** [comment]
Hey @YadavAkhileshh I can come up with some great background colours to make is more attractive if the issue is still open

**Comment by NITYANIT** [comment]
i can work on this issue,as i worked on it before

**Comment by NITYANIT** [comment]
please assign me this issue
