### ISSUE TITLE
need to update the documentation in readme.md

### ISSUE THREAD

**Issue by Gamerking177** [YadavAkhileshh/Alien-Invasion-Defense#12]
![image](https://github.com/user-attachments/assets/774002db-fec4-4cf4-8157-94e05b203cee)

need some changes in documentation ini github readme.nd

**Comment by AyutheCoder** [comment]
I can add document section in the website which can provide the following details,please label it under GSSOC Ext.24 and Hactoberfest

**Comment by Gamerking177** [comment]
@YadavAkhileshh  bro i rise this isue why u assigned him

**Comment by Gamerking177** [comment]
tell sir i raised this issue and u assigned to him it's unfair

**Comment by Gamerking177** [comment]
@YadavAkhileshh i am going to discord and tell this to gssoc

**Comment by AyutheCoder** [comment]
Sir,kindly provide label to it under GSSoc,Hacktoberfest

**Comment by yakhilgithub** [comment]
@AyutheCoder  issue is closed, so please raise another issue and proceed with working on it
