### ISSUE TITLE
 Feature Request: Levels and Difficulty Modes for Alien Invasion Defense Game.

### ISSUE THREAD

**Issue by smog-root** [YadavAkhileshh/Alien-Invasion-Defense#120]
Levels:

- Adding multiple levels with increasing difficulty would create a more engaging experience. Each level could introduce new alien types, challenges, and unique environments.

Difficulty Modes:

- Implementing "Easy" and "Hard" modes could cater to a wider audience.

- Easy Mode: Suitable for newcomers, with slower enemy spawn rates and more resources.

- Hard Mode: For experienced players, featuring faster enemy waves, limited resources, and additional challenges.

I'm expecting a gssoc-ext and a level3 label,  hacktoberfest-accepted.

Assign me!

**Comment by smog-root** [comment]
Can I get your discord?! Or can social to contact you??

**Comment by yakhilgithub** [comment]
https://www.linkedin.com/in/yakhilesh/

**Comment by YadavAkhileshh** [comment]
https://www.linkedin.com/in/yakhilesh/

**Comment by smog-root** [comment]
the feature is added by another contributer! i'm closing the issue!
