### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [YadavAkhileshh/Alien-Invasion-Defense#124]
Dear Project Admin, Alien-Invasion-Defense

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by AKSHITHA-CHILUKA** [comment]
hey @YadavAkhileshh please read what is mentioned above

**Comment by aditya-bhaumik** [comment]
hi @YadavAkhileshh she is part of the core team she was just trying to help you understand the guidelines

**Comment by MastanSayyad** [comment]
@YadavAkhileshh, Program Manager this side. Are you reading the issues properly? It seems like you're adding labels just by looking at the issue title.

While the labels you add seem correct, I request you to ensure that all necessary labels are added to all merged PRs. It's essential for contributors to track their PRs and scores on the leaderboard. Please do the needful.

![image](https://github.com/user-attachments/assets/1f6f64d8-d834-4811-8f8f-d4879a9077c9)

**Comment by YadavAkhileshh** [comment]
@AKSHITHA-CHILUKA I apologize for not thoroughly reviewing this issue and have concerns about the level label. Thank you for notifying me.

**Comment by YadavAkhileshh** [comment]
@MastanSayyad Do I need to assign labels to everyone when merging a pull request

**Comment by AKSHITHA-CHILUKA** [comment]
yeah you have to @YadavAkhileshh 
all issues and all pr's you should label and check the crt labels 
gssoc-ext
level1, level2, level3
hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

**Comment by Meetjain1** [comment]
@YadavAkhileshh level label is not correct , L is small not capital fix it asap!

**Comment by aditya-bhaumik** [comment]
@YadavAkhileshh please make the change asap as your contributors contributions are not getting counted in the leaderboard because of this
