### ISSUE TITLE
Add Floating Social Media Iconbar on homepage

### ISSUE THREAD

**Issue by AsmitaMishra24** [YadavAkhileshh/Alien-Invasion-Defense#148]
### 🎮 feature Request
I want to add a floating social media icon bar to the homepage of our website to improve user engagement by providing easy access to our social media profiles.

### Requirements
Position: The icon bar should be positioned on the left side of the screen.
Visibility: The bar should remain visible when the user scrolls up and down the home screen.
Icons: Include icons for Facebook, Twitter, Instagram, LinkedIn, and YouTube.
Links: Each icon should link to the corresponding social media profile.
Responsive Design: The icon bar should be responsive and should adjust to different screen sizes (desktop, tablet, mobile).
Hover Effect: When a user hovers over an icon, it should display the name of the social media platform.
Accessibility: Ensure the icon bar is accessible and follows best practices for screen readers.

### Screenshot:
![345800664-b46c5210-a8ef-4920-a3f8-565b04c01f3b](https://github.com/user-attachments/assets/0b340fe6-824e-4d30-ae34-035720ce530e)
![videoframe_0](https://github.com/user-attachments/assets/b63d333d-6656-404f-9367-a043cb302a8c)
![Screenshot 2024-07-05 180148](https://github.com/user-attachments/assets/f328b287-6c17-4a6d-a670-8fb59fcd722c)

**Comment by AsmitaMishra24** [comment]
Please assign me this issue under hacktoberfest 2024 and GSSOC'24 Extd

**Comment by AsmitaMishra24** [comment]
@YadavAkhileshh, please add hacktoberfest label also

**Comment by YadavAkhileshh** [comment]
@AsmitaMishra24  add the links on each and every icons

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 add the links on each and every icons

@YadavAkhileshh, Sure

**Comment by YadavAkhileshh** [comment]
@AsmitaMishra24 for links connect me on my LinkedIn

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 for links connect me on my LinkedIn

@YadavAkhileshh, I’ve sent you a request. You can connect with me and share the links.
