### ISSUE TITLE
[BUG] Spacebar is not working

### ISSUE THREAD

**Issue by Karan-Mahato** [YadavAkhileshh/Alien-Invasion-Defense#150]
### Description

In the code, the spacebar is used for shooting bullets, but in the deployment link, the spacebar is not working.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [x] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Deepak0yadav** [comment]
@Karan-Mahato  Space bar functionality is working but the issue is that for accessing the shoot functionality You need to press it continuously for longer duration .The responsiveness of the shoot command is affected by the duration of the press. A quick tap isn't registering properly

**Comment by Karan-Mahato** [comment]
@Deepak0yadav okay, thanks for explaining the issue
