### ISSUE TITLE
 No Local Storage in Game and No High Score Feature

### ISSUE THREAD

**Issue by PATILYASHH** [YadavAkhileshh/Alien-Invasion-Defense#158]
#### Description
Currently, the game does not implement local storage, and as a result, all game data is lost when the user refreshes the page. Additionally, there is no concept of a high score. By adding local storage and introducing a high score feature, we can ensure that the game state is preserved, and players can see their best performance across sessions.

#### Steps to Reproduce
1. Play the game and make progress.
2. Refresh the browser window.
3. Notice that all game data is lost.

#### Expected Behavior
- The game should save progress to local storage, so when the user refreshes the page, the game can restore the previous state.
- A high score feature should be added where the user's highest score is stored in local storage and displayed in future sessions.

#### Possible Solution
- Implement local storage to save game data (e.g., player progress, current score, etc.).
- Introduce a high score feature, saving the highest score in local storage and displaying it when the game is reloaded.

#### Screenshot
![image](https://github.com/user-attachments/assets/c69df289-9d13-44d2-8d50-1d3b2214c8da)

#### Additional Context
Adding local storage and a high score feature will significantly enhance the user experience by preserving progress and providing players with a goal to beat their previous best score.

**Comment by PATILYASHH** [comment]
Please assign this issue to me

**Comment by priyanshu1976** [comment]
@YadavAkhileshh  please assign me this issue under hacktoberfest accepted
