### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by Gamerking177** [YadavAkhileshh/Alien-Invasion-Defense#16]
![image](https://github.com/user-attachments/assets/bccd4d37-bec2-4e25-b609-858d04721163)

need some changes in readme.md

**Comment by Aryan01903** [comment]
pls assign this issue to me

**Comment by YadavAkhileshh** [comment]
@Gamerking177 Assigned

**Comment by Gamerking177** [comment]
@YadavAkhileshh pls also add hacktoberfest accepted label plss

**Comment by KVS-Sahithi** [comment]
Hi! I’d love to work on this issue to enhance the project. Could you please assign it to me?

**Comment by Gamerking177** [comment]
@YadavAkhileshh plss se my pr sir
