### ISSUE TITLE
Add a pause button (to pause the game once started)

### ISSUE THREAD

**Issue by ash-k121** [YadavAkhileshh/Alien-Invasion-Defense#17]

**Comment by GeorgiosDrivas** [comment]
Hello @YadavAkhileshh ! I would like to work on this issue.

**Comment by GeorgiosDrivas** [comment]
@YadavAkhileshh  Just a small detail about the UI before making a pull request. Would you like the pause functionality to be triggered when the player presses a key( for example the Escape key), or by pressing a button that is visible on the screen?

If a visible button on the screen is your choise, do you have a specific place you want that button to be?

Right now, I have created the pause feature when the player presses the escape key. It pauses the game and displays a button on the screen. When the player presses Escape again or the button, the game will continue from where it was paused. Do you like it that way?

![scr](https://github.com/user-attachments/assets/cbcf4ff9-df71-4976-ba79-9af4c4d7af83)

**Comment by YadavAkhileshh** [comment]
Yes @GeorgiosDrivas go for it

**Comment by GeorgiosDrivas** [comment]
Great, I created the pull request
