### ISSUE TITLE
changing aliens icons and adding stars to represent the background in a better way

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [YadavAkhileshh/Alien-Invasion-Defense#24]
i will change alien icons and they will be represented in different colors and i will add stars to present the game background in a better  way
please assign me with the required labels with respect to gssoc'24 extended program

**Comment by Akanshaku** [comment]
please assign me this issue I will change aliens icon and add stars.

**Comment by BVPKARTHIKEYA** [comment]
You can mark it as completed!!
Thanks for your Feedback!
