### ISSUE TITLE
[BUG] Fixing UI of signup page

### ISSUE THREAD

**Issue by Sourabh782** [YadavAkhileshh/Alien-Invasion-Defense#259]
### Description

the current signup page has unwanted horizontal and vertical scroll

### Screenshots

![image](https://github.com/user-attachments/assets/5bd56d20-f97d-4552-9359-0bb23d9ae8b4)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by GyanaPrakashSahoo7853** [comment]
###Description 

The current page lacks animation effect on Sign up page, it only change to blue color when someone hover on it, I have added 3D Hover effect on Sign Up page when someone hover on it . 

###Recordings

https://github.com/user-attachments/assets/6c541871-26d0-45c0-a1f0-43d82cd1bc08

I would like to work on it.
@YadavAkhileshh Please assign me this issue i want to change the sign up page with 3D animation .
