### ISSUE TITLE
Add Light Mode and also make rules in a separate page

### ISSUE THREAD

**Issue by t1nt1n-s0lv3r** [YadavAkhileshh/Alien-Invasion-Defense#3]
The rules of the game can be implemented in a separate page and allow the users to toggle between light mode and dark mode such that it will be easy for users to adjust the screen based on their comfort

Please assign it under gssoc '24 and hacktoberfest

**Comment by monishkumardvs** [comment]
can u assign it to me

**Comment by chmp0940** [comment]
can you assign it to me i had done it before also

**Comment by priyanshinegi07** [comment]
@YadavAkhileshh Can you please assign me this issue? I would like to work on it.

**Comment by batman-rises** [comment]
Sir, can u pls assign it to me I really  want to start with my open-source contributions asap already too late....Thank You.
