### ISSUE TITLE
Enter your name option

### ISSUE THREAD

**Issue by vijaychandra1910** [YadavAkhileshh/Alien-Invasion-Defense#36]
Add the option where user can enter there name and also show there name into the sidebar into the whole game.

**Comment by Hajer45** [comment]
Hello, can I work on this?

**Comment by vijaychandra1910** [comment]
yeah

**Comment by YadavAkhileshh** [comment]
@vijaychandra1910 any update?

**Comment by vijaychandra1910** [comment]
nope please unassign me and assign to someone.
