### ISSUE TITLE
[BUG] Add Translation Tool

### ISSUE THREAD

**Issue by Subhajit-2023-44** [YadavAkhileshh/Alien-Invasion-Defense#364]
### Description

I want to add a Translation Tool(all language) properly.

@YadavAkhileshh  PA please assign me this task.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh

**Comment by T-Rahul-prabhu-38** [comment]
@YadavAkhileshh can you assign me this issue.
