### ISSUE TITLE
Add some more good colours to the website to increase UX.

### ISSUE THREAD

**Issue by Vaibhav-Kumar10** [YadavAkhileshh/Alien-Invasion-Defense#41]
Modify the colours to make the website to be more attractive.
Green color is improved to any other color.

**Comment by Vaibhav-Kumar10** [comment]
Please assign me this issue for Hacktoberfest and GSSoC 2024 Extd

**Comment by Akanshaku** [comment]
Please assign me this issue under GSSoC'24 Extd.

**Comment by sahare-mayur-007** [comment]
PLZ ASSIGN ME THIS ISSUE UNDER GSSOC'24 EXTD

**Comment by gracetheresa** [comment]
I would like to make changes can you assign this issue

**Comment by Vaibhav-Kumar10** [comment]
Please update the label so that It can be counted in hactoberfest

**Comment by Akanshaku** [comment]
COLOR CHANGED #41

**Comment by Akanshaku** [comment]
#41 color changed
