### ISSUE TITLE
Improving the UI for the feedback form & redirection to home page

### ISSUE THREAD

**Issue by SrijaVuppala295** [YadavAkhileshh/Alien-Invasion-Defense#425]
## Description

This update enhances the user interface of the feedback form, making it more user-friendly and visually appealing. Additionally, the functionality for redirecting users to the home page after successful feedback submission has been implemented. This will provide a smoother user experience, ensuring users are guided back to the main page seamlessly after submitting their feedback.

## Screenshots :

![image](https://github.com/user-attachments/assets/b67d49e0-4591-45cd-94ee-0d58c1f00208)

**Comment by Subhajit-2023-44** [comment]
Duplicate #420
