### ISSUE TITLE
[Feature enhacement] : Dark mode Toggle.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [YadavAkhileshh/Alien-Invasion-Defense#43]
### **Is your feature request related to a problem? Please describe.**
there is no preferences in the website to toggle between dark and light mode.I will create a toggle in the navabar which will allow the user to toggle between dark mode and light mode.

**Comment by T-Rahul-prabhu-38** [comment]
I have called for a PR .

**Comment by BhaktiMore18** [comment]
Can I also work on the same issue?

**Comment by T-Rahul-prabhu-38** [comment]
@BhaktiMore18  oh i have aleady finished it brother,

**Comment by T-Rahul-prabhu-38** [comment]
@YadavAkhileshh  I have called for a PR , can u please check it.

**Comment by BhaktiMore18** [comment]
> @BhaktiMore18 oh i have aleady finished it brother,

Yeah bro, just checked it, can you suggest me similar issues to work on
