### ISSUE TITLE
[BUG] Make Game Responsive for Multiple Screen Sizes

### ISSUE THREAD

**Issue by srishti023** [YadavAkhileshh/Alien-Invasion-Defense#430]
### Description

I would like to enhance the user experience by making the game responsive across various devices, including mobile and tablet screens. Currently, the content does not adapt well to different screen sizes, which may impact user engagement.

### Screenshots

https://github.com/user-attachments/assets/3b1b9c58-ad4f-403f-a1a6-25b64d12cab9

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by srishti023** [comment]
hey @YadavAkhileshh before making the website responsive we need to adjust all the alignments first of this gaming website. so i am working on it or in progress i have done much enhancement for good layout 

![Screenshot 2024-10-21 002557](https://github.com/user-attachments/assets/794f2d38-f8de-4dab-bc60-11bb63058fb8)

**Comment by YadavAkhileshh** [comment]
@srishti023 any update??
