### ISSUE TITLE
[BUG] All buttons are overlapped

### ISSUE THREAD

**Issue by Prizag** [YadavAkhileshh/Alien-Invasion-Defense#440]
### Description

All the buttons are double or overlapped in the landing page which looks bad, please assign the task to me to fix this issue

### Screenshots

![Screenshot 2024-10-18 224857](https://github.com/user-attachments/assets/3b6e85a5-a65c-4b89-b92f-40a8ac7f0e7b)

### What browser are you seeing the problem on?

Firefox

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by anubhavvsharma** [comment]
I would like to fix this. @YadavAkhileshh
