### ISSUE TITLE
buttons are not good   

### ISSUE THREAD

**Issue by dipeshkumar799** [YadavAkhileshh/Alien-Invasion-Defense#442]
i want to make the pause,restart ..etc button good
and darmode is not working properly i will make it 
''
![BLOGS _ FINNEWS TEAM and 10 more pages - Personal - Microsoft​ Edge 18-10-2024 22_34_38](https://github.com/user-attachments/assets/6455262a-259a-47b1-b339-09c07b63b9fa)

@YadavAkhileshh :pls assign me  i will work on that.

**Comment by RAMIREDDYGAYATHRI02** [comment]
Yeah i will do it!
