### ISSUE TITLE
[BUG] Fix Registration page

### ISSUE THREAD

**Issue by KrishChothani** [YadavAkhileshh/Alien-Invasion-Defense#445]
### Description

There is show multiple registration page ..

### Screenshots

![image](https://github.com/user-attachments/assets/5d9407c3-6d85-41bd-8632-45fdda3cd477)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Nikhil-Banthia** [comment]
@YadavAkhileshh i can solve this issue please assign me this isuue and lable it as hacktober fest and level 1 issue

**Comment by KrishChothani** [comment]
As per the guidelines, please assign this task to me .
