### ISSUE TITLE
Feature Implementation: Donation/Sponsorship Page

### ISSUE THREAD

**Issue by Varsha-1605** [YadavAkhileshh/Alien-Invasion-Defense#456]
If applicable, provide information on how users can support the project financially.

@YadavAkhileshh  I would love to work on it, could you please assign this task to me??

**Comment by Varsha-1605** [comment]
@YadavAkhileshh hello!?

**Comment by YadavAkhileshh** [comment]
@Varsha-1605 Go for it

**Comment by Varsha-1605** [comment]
@YadavAkhileshh Thanks!
