### ISSUE TITLE
[BUG] So  much Misalignment of Elements and Duplicate Components (Volume Bar, Theme Toggle) Adjustment needed

### ISSUE THREAD

**Issue by srishti023** [YadavAkhileshh/Alien-Invasion-Defense#462]
### Description

I am facing alignment issues in the game where certain elements, are misaligned. Additionally, there are duplicate instances of these components in the HTML structure, which is causing further layout inconsistencies.

What I Tried:
I attempted to manually adjust the CSS styling for these elements, but the alignment still isn't working as expected.
I also tried restructuring the HTML to remove duplicates, but this led to unexpected behavior in the game interface.

we need to to implement correct structure and styling for better layout we need to use flexbox property .

I want to work on it please assign me this issue !

### Screenshots

Problem :

![Screenshot 2024-10-20 231633](https://github.com/user-attachments/assets/ad55bc18-efb3-421e-95fc-f7f0f78650af)
![Screenshot 2024-10-20 201337](https://github.com/user-attachments/assets/e4a07d09-49d8-4e88-a009-1e8f4c52961b)

I tried to make the sidebar section more structure with the help of correct html structuring and styling.

Result:

![Screenshot 2024-10-20 232913](https://github.com/user-attachments/assets/7978faa6-7ede-4afa-8a3a-92ced66a4071)

Overall the whole UI needs adjustment!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by anchalchaturvedi08** [comment]
Hello PA, I want to work on this issue. Can you assign it to me?
