### ISSUE TITLE
Github actions for more connectivity! 

### ISSUE THREAD

**Issue by smog-root** [YadavAkhileshh/Alien-Invasion-Defense#465]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @YadavAkhileshh

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by smog-root** [comment]
@YadavAkhileshh hey.. you have not added labels to my last PR!! 

https://github.com/YadavAkhileshh/Alien-Invasion-Defense/pull/437

**Comment by smog-root** [comment]
Add labels to my last PR! @YadavAkhileshh

**Comment by smog-root** [comment]
?? reply???? @YadavAkhileshh

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024

**Comment by Shalinis19137** [comment]
ok sir
