### ISSUE TITLE
[BUG]  No icon in login form!!!

### ISSUE THREAD

**Issue by SrijaVuppala295** [YadavAkhileshh/Alien-Invasion-Defense#477]
### Description

Adding icon so that titlebar looks good

### Screenshots

![image](https://github.com/user-attachments/assets/a51d2cb0-0958-44ac-8a87-c49c3e336b34)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by SrijaVuppala295** [comment]
@YadavAkhileshh , please assign me under this issue

**Comment by RAMIREDDYGAYATHRI02** [comment]
@SrijaVuppala295 Yeah i can do it! can please assign me under this bug
