### ISSUE TITLE
NOTICE : GSSoC Extd (Core Team)

### ISSUE THREAD

**Issue by Meetjain1** [YadavAkhileshh/Alien-Invasion-Defense#486]
**Notice:**  

Hi @YadavAkhileshh .

As per the guidelines issued to you earlier, We are reminding you again to Add the **Program Manager** @MastanSayyad and @sanjay-kv as a collaborator to this repository.

Adding the Program Manager is **compulsory** for **removal of spam from the leaderboard** and to maintain the integrity of contributions.  

⚠️ **Note:** If the Program Manager is already added, kindly ignore this message.  

Thank you for your cooperation!
Core Team
GSSoC-Extd

**Comment by Meetjain1** [comment]
Gentle remainder @YadavAkhileshh

**Comment by YadavAkhileshh** [comment]
@Meetjain1 already I have sent them a collaborator request....

**Comment by Meetjain1** [comment]
> @Meetjain1 already I have sent them a collaborator request....

Okay thanks @YadavAkhileshh
