### ISSUE TITLE
[⭐FEATURE] Add a Visitor Counter feature ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [YadavAkhileshh/Alien-Invasion-Defense#491]
### Description

I want to add a Visitor Counter feature properly.

@YadavAkhileshh  PA please assign me this task.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by YadavAkhileshh** [comment]
@Subhajit-2023-44 Go for it

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Go for it

Okay but please merge my pr, otherwise i can't able to do another work
