### ISSUE TITLE
proper name and logo for this game 

### ISSUE THREAD

**Issue by kashishchadha** [YadavAkhileshh/Alien-Invasion-Defense#52]

**Comment by AtharvaTayade1** [comment]
I can Add a much better logo for the game improve its individuality in gaming arena... 
Also can improve the name
can you assign me the issue and list it under GS-SOC ext?

**Comment by sayiamarora** [comment]
Hey @YadavAkhileshh Can I work on this issue as I can design a user attractive logo for the same.

**Comment by YadavAkhileshh** [comment]
@kashishchadha DONE??
