### ISSUE TITLE
Improve ui and confirmation message of feedback form

### ISSUE THREAD

**Issue by ananyag309** [YadavAkhileshh/Alien-Invasion-Defense#524]
### Description

enhance ui, fix the rating validation, and add confirmation message to feedback form

### Screenshots

![image](https://github.com/user-attachments/assets/ef11cb2f-cd43-41e1-8e70-3efe42b6bd34)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by RAMIREDDYGAYATHRI02** [comment]
Yeah i can do it!
