### ISSUE TITLE
Add Google Authentication

### ISSUE THREAD

**Issue by amitb0ra** [YadavAkhileshh/Alien-Invasion-Defense#525]
### Description

Currently, the Alien Invasion Defense project uses manual authentication only. We need to implement Google authentication to enhance the user login experience.

### Any additional information?

Please assign this issue to me under **gssoc-ext** and **hacktober fest** labels.

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task with difficulty label
