### ISSUE TITLE
Signup Register page 

### ISSUE THREAD

**Issue by mvinodkumar9381** [YadavAkhileshh/Alien-Invasion-Defense#530]
![image](https://github.com/user-attachments/assets/0503fa97-a2cc-49fc-982b-08610cc7cf28)

 The signup/Register can replace to the starting page of the game so the Adventure to name them.

**Comment by mvinodkumar9381** [comment]
Please assign it and give labels

**Comment by mvinodkumar9381** [comment]
@YadavAkhileshh  Please assign it and give labels

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task with difficulty label
