### ISSUE TITLE
Creating a Logo for the webiste !!!

### ISSUE THREAD

**Issue by SrijaVuppala295** [YadavAkhileshh/Alien-Invasion-Defense#534]
![image](https://github.com/user-attachments/assets/cff18add-6fd0-4f3e-8e5d-605f29b42357)

**Comment by SrijaVuppala295** [comment]
Please assign  me under this issue !!! @YadavAkhileshh

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
