### ISSUE TITLE
Feature : Changing the background of the feedback page !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [YadavAkhileshh/Alien-Invasion-Defense#535]
![image](https://github.com/user-attachments/assets/78b74032-d4b4-4caa-93f8-0becea544f24)

@YadavAkhileshh , please assign me under this issue !!! I make the snowfall background and change the title bar and add icon in the titlebar !!

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task with difficulty label
