### ISSUE TITLE
[FEATURE] Add a pop up dialog box for subscribing to newsletter ✨✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [YadavAkhileshh/Alien-Invasion-Defense#541]
### Description

I want to add a pop up dialog box for subscribing to newsletter..

PA please assign me for this task..

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh

**Comment by BarryByte** [comment]
@YadavAkhileshh Please assign me this issue.

**Comment by Subhajit-2023-44** [comment]
> @YadavAkhileshh Please assign me this issue.

😄but why ??
