### ISSUE TITLE
FEATURE: ENHANCEMENT IN "What Our Players Are Saying" SECTION

### ISSUE THREAD

**Issue by isimarjitsingh** [YadavAkhileshh/Alien-Invasion-Defense#568]
### Feature Summary

AS i observe the designing of this section is pretty ordinary and the numbers of card is also low .

### Description

i wiil be able to give good designing to this cards , increase the number strength of cards and also provide the carousel effect in it with the help of js

### Screenshots/Logs

CURRENT DESIGNING:-
![Screenshot 2024-10-28 211544](https://github.com/user-attachments/assets/46482016-c5e8-417d-9992-a5c8e00d2c56)

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by ayushdubey570** [comment]
@YadavAkhileshh /assign me this issue.
