### ISSUE TITLE
enchancing the appearance of privacy policy page

### ISSUE THREAD

**Issue by Riyachauhan11** [YadavAkhileshh/Alien-Invasion-Defense#582]
I would liek to improve the appearance of privacy policy page as it looks too simple right now.
![image](https://github.com/user-attachments/assets/cfd17102-0fd5-4214-8d42-6f87d5559329)

**Comment by Vijeth-Kumar-18** [comment]
I would like to add some button and also improve the appearace of this page , as it is too simple . Please assign it to me
