### ISSUE TITLE
Enhance Game Graphics for a More Realistic Experience

### ISSUE THREAD

**Issue by harshpareshbhaigosalya** [YadavAkhileshh/Alien-Invasion-Defense#60]
Currently, the game uses basic shapes to represent various elements like aliens and background. To make the game more visually appealing and realistic, we need to add graphical elements, including:
1) Custom background images.
2) Improved animations and effects

consider it under:
hacktoberfest-accepted
gssoc-2024-extended

Thank You!

![Screenshot 2024-10-04 012630](https://github.com/user-attachments/assets/47a289ca-01b9-4d23-844a-d8e553d531e1)

![Screenshot 2024-10-04 012646](https://github.com/user-attachments/assets/2aa29b98-0337-4fc7-924b-9277efa62b3b)

**Comment by Om-Thanage** [comment]
I would like to work on this

**Comment by harshpareshbhaigosalya** [comment]
I have already done!
Plz @YadavAkhileshh  send your consent so I can PR you!
Thank you!
consider it under:
hacktoberfest-accepted
gssoc-2024-extended
