### ISSUE TITLE
Alignment of the program section

### ISSUE THREAD

**Issue by Aman-G-upta** [YadavAkhileshh/Alien-Invasion-Defense#606]
![Screenshot 2024-10-29 083757](https://github.com/user-attachments/assets/3935bec7-83b9-41e7-8379-1f6c45018838)

Please assign me under this issue @YadavAkhileshh

**Comment by Rishithagaddam** [comment]
@Aman-G-upta Can u assign me this?

**Comment by Rishithagaddam** [comment]
👍🏻 okay
