### ISSUE TITLE
FEATURE:Adding a visitor counter

### ISSUE THREAD

**Issue by Peart-Guy** [YadavAkhileshh/Alien-Invasion-Defense#639]
### Feature Summary

I want to add a visitor counter to the website

### Description

My contribution will show the counter of visitors

### Proposed Solution

I wil make a counter using HTML,CSS, JavaScript

### Screenshots/Logs

![Screenshot 2024-10-31 141146](https://github.com/user-attachments/assets/9589aaf6-bd74-436a-9fd7-a83757d06fe3)

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by Peart-Guy** [comment]
@YadavAkhileshh  
Kindly assign me the issue

**Comment by YadavAkhileshh** [comment]
@Peart-Guy go for it
