### ISSUE TITLE
Proper Alignment of Logo and score Board on Home Page of Game...

### ISSUE THREAD

**Issue by AtharvaTayade1** [YadavAkhileshh/Alien-Invasion-Defense#64]
<img width="1440" alt="Screenshot 2024-10-04 at 20 03 32" src="https://github.com/user-attachments/assets/63755a41-943f-4b2e-a721-912ab0e253e2">

Herein proper alignment cane be made for top left logo and bottom left score as well

**Comment by AtharvaTayade1** [comment]
I can work on this issue 
Can you please assign it to me

**Comment by sayiamarora** [comment]
Hey @YadavAkhileshh can I work on this issue. As I can see this issue is not attended or not resolved

**Comment by AtharvaTayade1** [comment]
> Hey @YadavAkhileshh can I work on this issue. As I can see this issue is not attended or not resolved

Hi bro why don't you pick out something else I am gr8 at this right now
Thank you
