### ISSUE TITLE
Request for Contribution: In-Game Store Feature

### ISSUE THREAD

**Issue by BigBang001** [YadavAkhileshh/Alien-Invasion-Defense#65]
I am interested in contributing to the **Alien Invasion Defense** project and would like to propose the addition of an **In-Game Store** feature. This would enhance the gameplay experience by allowing players to purchase upgrades with currency earned during the game.

**Proposed Features:**
- In-game currency system to reward players.
- A UI for players to view and purchase upgrades.
- Various upgrade options like enhanced weapons and extra lives.

**Request for Assignment:**
Kindly assign this issue to me for contribution under **GSSoC-extd** and **Hacktoberfest 2024**.

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
