### ISSUE TITLE
BUG: start game, pause button , light mode vote popup not visible 

### ISSUE THREAD

**Issue by Riyachauhan11** [YadavAkhileshh/Alien-Invasion-Defense#677]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

After the website animation plays the start game and pause button arent visible. 
also the light mode vote popup doesnt look well.

### Steps to Reproduce

run the website

### Screenshots/Logs

![382739931-3c660e1d-97e6-45ec-9dc2-b8cb5050e058](https://github.com/user-attachments/assets/59ae6b59-a1a1-4bfd-b513-670b2d1691e0)
![image](https://github.com/user-attachments/assets/1bb361bf-4cb2-4feb-bfad-ff5f7acf2872)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by YadavAkhileshh** [comment]
@Riyachauhan11 go for it
