### ISSUE TITLE
BUG: buttons misalignment issue

### ISSUE THREAD

**Issue by Subhajit-2023-44** [YadavAkhileshh/Alien-Invasion-Defense#753]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

I want to fixed this issue

![Screenshot 2024-11-09 155618](https://github.com/user-attachments/assets/58081cb8-5d43-4f2c-ab33-c73e57b860f7)

### Steps to Reproduce

.

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by tharikashree** [comment]
Hey can i work on this

**Comment by Subhajit-2023-44** [comment]
> Hey can i work on this

already done
