### ISSUE TITLE
adding favicon icon

### ISSUE THREAD

**Issue by solanki505** [YadavAkhileshh/Alien-Invasion-Defense#81]
![Screenshot 2024-10-05 221123](https://github.com/user-attachments/assets/c0ec9bde-4c5e-4917-9839-026cdcc9ae6e)

**Comment by Mirnalkishor** [comment]
I want to work on this issue

**Comment by 4F24L** [comment]
Can i wirk on this issue ?? @YadavAkhileshh

**Comment by solanki505** [comment]
i want to work on this issue
