### ISSUE TITLE
Adding a new selector tool for user to select background color

### ISSUE THREAD

**Issue by Vaibhav-Kumar10** [YadavAkhileshh/Alien-Invasion-Defense#83]
The background color is fixed.
To make the website more responsive, a selector tool must be added for user so that they can adjust the background as per their wish.

This will make the website more user friendly.

**Comment by Vaibhav-Kumar10** [comment]
Please assign me this issue as per GSSOCEXTD and hactoberfest

**Comment by swethapadmavathimukku** [comment]
Hi @YadavAkhileshh, I would like to work on this issue of adding different backgrounds, could you please assign me this issue

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this under GSSoC'24 Extd @YadavAkhileshh
