### ISSUE TITLE
Add shields (block bombs) power-up.

### ISSUE THREAD

**Issue by AayushiJapsare15** [YadavAkhileshh/Alien-Invasion-Defense#86]
Even if it is mentioned in the manual no shield power-up is descended. I would to add it along with other power-ups.
![image](https://github.com/user-attachments/assets/99fe82b7-8cc9-4ef7-98f2-91177699f188)
Once the player catches it. It will create a shield around the device for 3 secs ( or according to your preference )

**Comment by AayushiJapsare15** [comment]
@YadavAkhileshh please assign me this feature if you found the approach interesting or recommend changes if any.

**Comment by swethapadmavathimukku** [comment]
@YadavAkhileshh  I would like to work on adding the power-up shields to the game 

could you please assign me on this issue

**Comment by AayushiJapsare15** [comment]
@YadavAkhileshh can you please assign it to e so that I can start working on the feature
