### ISSUE TITLE
Adding a Pause option.

### ISSUE THREAD

**Issue by AayushiJapsare15** [YadavAkhileshh/Alien-Invasion-Defense#88]
Adding a pause option is essential because, when users switch tabs, the game continues and all power-ups drop in a line and in large numbers, disrupting the balance and flow. This feature will ensure smooth gameplay

![image](https://github.com/user-attachments/assets/0dafab9f-7444-4098-af63-1fe57fada0ea)

**Comment by AayushiJapsare15** [comment]
@YadavAkhileshh  Can you please add hacktoberfest-accepted and level tag.

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
