### ISSUE TITLE
Including play again button

### ISSUE THREAD

**Issue by sairampolisetty** [YadavAkhileshh/Alien-Invasion-Defense#9]
I think it would be better if  we add Play again button which will start the game again.

**Comment by simmi-verma** [comment]
I would like to work on this. please assign to me. first time I am contributing in gssoc-ext 24. Could you add gssoc label?

**Comment by thejatingupta7** [comment]
i would like to make a better animated play again button for this one:

**Comment by sairampolisetty** [comment]
@YadavAkhileshh Please check me PR.
