### ISSUE TITLE
Colors and Font of How to play can be improved

### ISSUE THREAD

**Issue by kanduru-abhiram** [YadavAkhileshh/Alien-Invasion-Defense#95]
Hello @YadavAkhileshh,

This issue is raised on a feature improvement
The How to play dropdown fonts and colors can be improved. And transition speed can be decreased for a good animation.

Kindly assign me this issue under Hacktoberfest 2024.

![image](https://github.com/user-attachments/assets/4e2e00d9-481b-471e-ac0d-36ea88ebd862)

**Comment by kanduru-abhiram** [comment]
Kindly assign me this issue under Hacktoberfest and Hacktoberfest2024

**Comment by MrSwapnilRahate** [comment]
I'm ready contribute. Please assign this to me under Hacktoberfest2024.

**Comment by kanduru-abhiram** [comment]
@MrSwapnilRahate, I am already working on this issue, please create new issue.

**Comment by MrSwapnilRahate** [comment]
Hi @YadavAkhileshh as @kanduru-abhiram suggestions if you need any help then please create new issue under Hactoberfest2024 and assign it to me.
